name: CI

on:
  workflow_dispatch:
  
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'logo/**'

jobs:
  test:
    name: 'Run Unit Test: node-16, ubuntu-latest'
    timeout-minutes: 10
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: reliable_unittest
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup docker
        uses: docker-practice/actions-setup-docker@1.0.9

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install deps
        run: npm install

      - name: Run ci
        run: npm run ci

      - name: Codecov
        uses: codecov/codecov-action@v3.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}